### PR TITLE
ldap2s3: decommissioned in favor of ldap_to_cis [IAM-858]

### PR DESCRIPTION
**Pull request by floatingatoll**
Per IAM-858, we're no longer using ldap2s3, and so we should remove all leftover traces of it from this repository. I chose to keep the ldap2s3/README with a deprecation note at top to support eventual decom efforts.

### CODE REVIEW

**Comment by floatingatoll** [comment]
@duallain FYI, there's a list of Mozilla ARNs in the LDAP/ldap2s3/README.md removed by this PR that may be useful to any cleanup tickets you have in flight.

**Comment by floatingatoll** [comment]
Restructured to leave the README in place for decom support, so that this can be merged.

**Review by gcoxmoz — APPROVED** [review]
As puppet-owner/owner of the current scripts, I approve this message.

**Comment by floatingatoll** [comment]
Verbal r+ received from gc for the addition of c1c0c2a.

**Pull request merged**
